### ISSUE TITLE
No way to set custom error message

### ISSUE THREAD

**Issue by aleshchenko** [intbot/ng2-pdfjs-viewer#10]
```javascript
this.service.loadFile().subscribe(
  blobFile => {
    this.pdfViewer.pdfSrc = blobFile;
    this.pdfViewer.refresh();
  },
  error => {
    this.pdfViewer.setError('Error loading PDF'); // this doesn't work :(
    this.pdfViewer.refresh();
  }
);
```

**Comment by codehippie1** [comment]
What are you trying to achieve here? I do not think 'setError' is a valid method on this component

**Comment by aleshchenko** [comment]
the idea is to have something like this with custom message:
![error](https://user-images.githubusercontent.com/4508521/46137742-ef23ae80-c252-11e8-8918-a3ee19603a90.png)

**Comment by codehippie1** [comment]
I get it now. Will have to check how to pass it to the underlying control.

**Comment by codehippie1** [comment]
@aleshchenko @bbrunda I started upgrading the package to ng 7. Will try to implement this as part of the upgrade.

**Comment by codehippie1** [comment]
Upgraded to angular 7. @aleshchenko @bbrunda Expect this implementation in the coming week.

**Comment by codehippie1** [comment]
Sorry for the delay. Being looked at now.

**Comment by codehippie1** [comment]
Finally, this is implemented. Get latest version from npm(As of now v3.4.5)

**Comment by codehippie1** [comment]
@aleshchenko @bbrunda  Finally, this is implemented. Get latest version from npm(As of now v3.4.5)
