### ISSUE TITLE
[externalWindow]="true" Doesn't Work with Blob in IE 11

### ISSUE THREAD

**Issue by maks-humeniuk** [intbot/ng2-pdfjs-viewer#100]
`[externalWindow]="true"` doesn't work with blob in IE 11. [Demo](https://ng2-pdfjs-viewer.azurewebsites.net/) page isn't even opening there.

**Comment by codehippie1** [comment]
@Halfist PDFJS documentation states limited support on IE. You may find an earlier solved issue on IE in closed issues with workarounds

**Comment by codehippie1** [comment]
The upgrade is underway to v 4.x. Hopefully, this will be addressed with upgrade. Fingers crossed
