### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by rakesh0r** [intbot/ng2-pdfjs-viewer#102]
Generic type is missing

```
ERROR: node_modules/ng2-pdfjs-viewer/index.d.ts:4:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

4     static forRoot(): ModuleWithProviders;
                        ~~~~~~~~~~~~~~~~~~~

An unhandled exception occurred: node_modules/ng2-pdfjs-viewer/index.d.ts:4:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

4     static forRoot(): ModuleWithProviders;
                        ~~~~~~~~~~~~~~~~~~~

See "/private/var/folders/n2/snmpy18s6k78wl38lb3hdr0r0000gn/T/ng-FawP4Q/angular-errors.log" for further details.
```

**Comment by denis-starchenko** [comment]
+ Please to add Angular 10 support

**Comment by jordankkk** [comment]
> I try to update angular version and have following problem. After running command `ng update @angular/cli @angular/core` appears following message:
> 
> ```
> Package "ng2-pdfjs-viewer" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0" (extended), would install "10.0.0").
> ✖ Migration failed: Incompatible peer dependencies found.
> ```
> 
> Please to add Angular 10 support.
> 
> Error found in the ng2-pdfjs-viewer version 5.0.7.

have to add --force to update

**Comment by TheParad0X** [comment]
+1 :)

**Comment by codehippie1** [comment]
@TheParad0X @jordankkk @denis-starchenko @rakesh0r This change is just done. A build will be provided soon

**Comment by mehulbhuva** [comment]
@codehippie1 - Is this component compatible with Angular 10. I see that you had the changes ready. Am facing upgrade issues from Angular 9 to Angular 10. When can we get a new build version for this component?

**Comment by BallisticPain** [comment]
I can see that the fix is in the [code](https://github.com/intbot/ng2-pdfjs-viewer/blob/master/dist/index.d.ts#L4). However, I'm still getting an error after running `npm install --update ng2-pdfjs-viewer`.

Error
```
ng serve
Compiling ng2-pdfjs-viewer : module as esm5

chunk {main} main.js, main.js.map (main) 2.08 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 724 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 14 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 344 kB [initial] [rendered]
Date: 2020-08-12T20:30:55.934Z - Hash: f67c5c8b7f866a6d80bf - Time: 3125ms

ERROR in node_modules/ng2-pdfjs-viewer/index.d.ts:4:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

4     static forRoot(): ModuleWithProviders;
                        ~~~~~~~~~~~~~~~~~~~
```

@codehippie1 I imagine this is due to it not being published to NPM. Do you have a plan on when you're going to publish?

Thanks!
Jarvis

**Comment by TheParad0X** [comment]
As a workaround, I removed ng2-pdfjs-viewer from my package.json, I migrated to the latest Angular 10, and then I added it again.

**Comment by thimma11** [comment]
Any update on this? It would be very helpful if the change would be published to npm.

**Comment by thimma11** [comment]
> I can see that the fix is in the [code](https://github.com/intbot/ng2-pdfjs-viewer/blob/master/dist/index.d.ts#L4). However, I'm still getting an error after running `npm install --update ng2-pdfjs-viewer`.
> 
> Error
> 
> ```
> ng serve
> Compiling ng2-pdfjs-viewer : module as esm5
> 
> chunk {main} main.js, main.js.map (main) 2.08 kB [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 724 bytes [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 14 kB [initial] [rendered]
> chunk {vendor} vendor.js, vendor.js.map (vendor) 344 kB [initial] [rendered]
> Date: 2020-08-12T20:30:55.934Z - Hash: f67c5c8b7f866a6d80bf - Time: 3125ms
> 
> ERROR in node_modules/ng2-pdfjs-viewer/index.d.ts:4:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
> 
> 4     static forRoot(): ModuleWithProviders;
>                         ~~~~~~~~~~~~~~~~~~~
> ```
> 
> @codehippie1 I imagine this is due to it not being published to NPM. Do you have a plan on when you're going to publish?
> 
> ...
> 
> I have successfully attempted to use the master branch (where these changes have been applied). Here is what I did for others that may need to use it before it is released to NPM.
> 
> 1. `npm install --save intbot/ng2-pdfjs-viewer#master`
> 2. Changed `import { PdfJsViewerModule } from 'ng2-pdfjs-viewer';` to `import ... from 'ng2-pdfjs-viewer/dist';`
> 3. `ng serve` Now it's working.
> 
> Thanks!
> Jarvis

Hi Jarvis!

Thanks for your workaround.

Unfortunately I'm getting
`Module not found: Error: Can't resolve 'ng2-pdfjs-viewer'`
after running ng serve.

Any idea why?

**Comment by thimma11** [comment]
> I can see that the fix is in the [code](https://github.com/intbot/ng2-pdfjs-viewer/blob/master/dist/index.d.ts#L4). However, I'm still getting an error after running `npm install --update ng2-pdfjs-viewer`.
> 
> Error
> 
> ```
> ng serve
> Compiling ng2-pdfjs-viewer : module as esm5
> 
> chunk {main} main.js, main.js.map (main) 2.08 kB [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 724 bytes [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 14 kB [initial] [rendered]
> chunk {vendor} vendor.js, vendor.js.map (vendor) 344 kB [initial] [rendered]
> Date: 2020-08-12T20:30:55.934Z - Hash: f67c5c8b7f866a6d80bf - Time: 3125ms
> 
> ERROR in node_modules/ng2-pdfjs-viewer/index.d.ts:4:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
> 
> 4     static forRoot(): ModuleWithProviders;
>                         ~~~~~~~~~~~~~~~~~~~
> ```
> 
> @codehippie1 I imagine this is due to it not being published to NPM. Do you have a plan on when you're going to publish?
> 
> ...
> 
> I have successfully attempted to use the master branch (where these changes have been applied). Here is what I did for others that may need to use it before it is released to NPM.
> 
> 1. `npm install --save intbot/ng2-pdfjs-viewer#master`
> 2. Changed `import { PdfJsViewerModule } from 'ng2-pdfjs-viewer';` to `import ... from 'ng2-pdfjs-viewer/dist';`
> 3. `ng serve` Now it's working.
> 
> Thanks!
> Jarvis

Hi @BallisticPain !

Thanks for your workaround.

Unfortunately I'm getting
`Module not found: Error: Can't resolve 'ng2-pdfjs-viewer'`
after running ng serve.

Any idea why?

**Comment by NicoPanduro** [comment]
@codehippie1 Any chance we can get the latest version published, so we can upgrade to A10 without hacks?

**Comment by i7i5** [comment]
@codehippie1 Any news, we actually migrate to Angular 10.

**Comment by Same17** [comment]
@codehippie1  Are there any news? We actually migrated to Angular 10 and we would like to have a published version. Thanks a lot!

**Comment by i7i5** [comment]
@Same17 This lib is dead as noone is working on it. We migrated to another lib as we raised angular versions.

**Comment by TheParad0X** [comment]
@i7i5 which one?

**Comment by i7i5** [comment]
@TheParad0X we switched to ngx-extended-pdf-viewer.
BR

**Comment by codehippie1** [comment]
@rakesh0r @BallisticPain @TheParad0X @i7i5 Sorry for being away for a while. Pandemic and homeschooling consumed all the time. :-).  Will update the library soon. (For any upgrades like this, if any of you had time, send in a pull request, will push a build).

**Comment by mehulbhuva** [comment]
@codehippie1 - Have you updated ng2-pdfjs-viewer to support Angular 10 yet? Can you please do this?

**Comment by codehippie1** [comment]
@rakesh0r @BallisticPain @TheParad0X @i7i5 @mehulbhuva @Same17 @NicoPanduro @thimma11 @jordankkk @denis-starchenko Angular version is updated to @angular V 11.2.3. Please upgrade the npm package to 6.0.1 for this
