### ISSUE TITLE
Click event of PDF

### ISSUE THREAD

**Issue by shahmeet999** [intbot/ng2-pdfjs-viewer#107]
My requirement is to get the click event of pdf and want to get the X and Y Coordinates and page number on which the click is done on pdf in angular.

Thanks in advance.

**Comment by codehippie1** [comment]
This is out of scope of this project and its capabilities.

Though, @shahmeet999 This is a wrapper of PDFJS, you may find exposed PDFJS objects you can work with. Please check documentation. If PDFJS is capable of handling your requirements, you can use these objects to get this done.

**Comment by codehippie1** [comment]
@shahmeet999 A googling gave me this. You may start there -> https://github.com/mozilla/pdf.js/issues/6471#issuecomment-154085128

**Comment by codehippie1** [comment]
Closing due to non-activity or updates
