### ISSUE TITLE
Angular 10 Support

### ISSUE THREAD

**Issue by thomas3577** [intbot/ng2-pdfjs-viewer#108]
If i try to update to Angular 10, I get the following Error:

`                  Package "ng2-pdfjs-viewer" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0" (extended), would install "10.0.3").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\thuber\AppData\Local\Temp\ng-51oPDz\angular-errors.log" for further details.
`

**Comment by codehippie1** [comment]
@thomas3577 Just merged a pull request from a contributor to address this. Will create a new build and keep you posted
