### ISSUE TITLE
Minified Files Not Being Used

### ISSUE THREAD

**Issue by tsmith3480** [intbot/ng2-pdfjs-viewer#114]
The script files pdf.js, pdf.worker.js and viewer.js have been minified (issue #22 ), but those versions are not being used. Can the module be updated to use those versions in a production build?

**Comment by codehippie1** [comment]
@tsmith3480 Will take a look

**Comment by jordanorc** [comment]
Same problem here. And the source maps are also included in the build. Any workaround?

**Comment by codehippie1** [comment]
Tracked on another issue. Will be fixed after 4.x upgrade
