### ISSUE TITLE
How to implement event bus?

### ISSUE THREAD

**Issue by pptyasar** [intbot/ng2-pdfjs-viewer#124]
Pdf js provides Third party viewer usage as in  https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage,

How to achieve this in ng2-pdfjs-viewer

**Comment by codehippie1** [comment]
@pptyasar If you look into the code/documentation - You may see that PDFViewerApplication object and PDFViewerApplicationOptions objects are exposed via get(), Follow mozilla's documentation from the link you provided once you get hold of these objects.

**Comment by codehippie1** [comment]
The upgrade is underway to v 4.x. Closing as this is tracked under enhancement. eventbus would be supported after the upgrade. Samples will be updated as well.
