### ISSUE TITLE
File local loading get "Unexpected server response (0)" (Offline - iOS)

### ISSUE THREAD

**Issue by sgabb** [intbot/ng2-pdfjs-viewer#129]
Hello, I'm encountering a weird error when trying to load a Blob saved locally (temporary stored in IndexedDB) while offline (no internet connection).
Unfortunately this is an issue only on iOS Safari (^_^)''

The error is:
**PDF.js v2.2.171 (build: c8c937c2) Unexpected server response (0) while retrieving PDF "blob?:https://[app-domain]/[fileUrl]". undefined**
Where [app-domain] is the same domain where the app frontend is served (no calls to a different origin server are done) and [fileUrl] I imagine is the Object URL created [here](https://github.com/intbot/ng2-pdfjs-viewer/blob/master/src/ng2-pdfjs-viewer.component.ts#L185)

By looking at the Network tab in the Debug console, it actually seems like a security issue:
- it specify the Initiator is pdf.js:23477, which should be [here](https://github.com/mozilla/pdf.js/blob/d7afb74a6e1980da5041f376e7a7c7caef5f42ea/src/display/network.js#L108)
- the xhr requests fails because "the resource requested is insecure"
- "Failed to load resource" impossible to complete the operation (Error WebKitBlobResource 1)

The point is that I am using Service Worker and cache to serve the app, and the error happens when the network is actually offline (no problem on Android).

Anyone can give me some advice on possible solutions and/or other places where I can ask for suggestions?

I added an issue also directly in PDF.js issue tracker: https://github.com/mozilla/pdf.js/issues/12967#issue-802927639

Thank you in advance!

**Comment by codehippie1** [comment]
@sgabb iOS Safari might be playing a role here. Have you tried this directly on the pdfjs viewer itself?

**Comment by codehippie1** [comment]
Closing as no response.
