### ISSUE TITLE
compatibility with IE 11

### ISSUE THREAD

**Issue by sai2812** [intbot/ng2-pdfjs-viewer#13]
your angular sample code  as well as application  does not work in IE 11 can you please check it once... its showing error

**Comment by KlausHans** [comment]
You'll need to uncomment some Polyfills in the polyfill.ts file of the Angular application. It Works in IE11.

**Comment by codehippie1** [comment]
@KlausHans Thanks for the response. Would you be able to comment with the exact lines you needed to comment to make it work for IE11

**Comment by KlausHans** [comment]
Of course. In the polyfills.ts (same level in the angular project like the index.html) just uncomment the import lines:

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 //import 'core-js/es6/symbol';
 //import 'core-js/es6/object';
 //import 'core-js/es6/function';
 //import 'core-js/es6/parse-int';
 //import 'core-js/es6/parse-float';
 //import 'core-js/es6/number';
 //import 'core-js/es6/math';
 //import 'core-js/es6/string';
 //import 'core-js/es6/date';
 //import 'core-js/es6/array';
 //import 'core-js/es6/regexp';
 //import 'core-js/es6/map';
 //import 'core-js/es6/weak-map';
 //import 'core-js/es6/set';

**Comment by codehippie1** [comment]
Marking this as solved. Added relevant labels for others to find it easy.
