### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by dedaimia** [intbot/ng2-pdfjs-viewer#130]
Could you please tag which commits/branches correspond to your released version on npmjs.com?     
Makes it a lot easier when troubleshooting problems if can look at the exact code version we're running. 

Specifically we're looking for which commit corresponds to the current (5.0.7) version.

**Comment by codehippie1** [comment]
@dedaimia  Started doing this with version 6.0.1. Hopefully I won't forget to do this going forward.
