### ISSUE TITLE
Remove header toolbar

### ISSUE THREAD

**Issue by faizaldong** [intbot/ng2-pdfjs-viewer#133]
Hi Maintainer,

As title mentioned, in your library is there any variable that we can pass to remove the top toolbar? I want the library to display the pdf only without the toolbar at the top. I had try to set all necessary variable to false, but only few button got hide.

thank you.

<img width="1026" alt="Screenshot 2021-03-16 at 9 36 44 AM" src="https://user-images.githubusercontent.com/17352624/111243057-50b28000-863b-11eb-9cc1-c260a2e87428.png">

**Comment by codehippie1** [comment]
@faizaldong You may use simple javascript visibility:hidden to achieve this. Better yet - jQuery would be a breeze. I will keep this in backlog as a nice to have and will get to it eventually as time permits. Also - Please send in a pull request with this feature implemented - would be happy to merge

**Comment by codehippie1** [comment]
Closing as out of scope
