### ISSUE TITLE
PDF viewer set full width

### ISSUE THREAD

**Issue by faizaldong** [intbot/ng2-pdfjs-viewer#136]
Hi maintainer,

Please refer attached image below. What I want to achieve is to make the width for all pages as full width. From the image below, you can see the first page of the pdf, the size is full width, I did it by hijacking the style from the browser. Is there any work around to achieve this?

Thanks!

<img width="329" alt="Screenshot 2021-03-23 at 12 43 37 PM" src="https://user-images.githubusercontent.com/17352624/112094081-93dd9780-8bd5-11eb-83a4-676af38a35f4.png">

**Comment by codehippie1** [comment]
The upgrade is underway to v 4.x. Closing as this will be addressed after upgrade.
