### ISSUE TITLE
Can't use fullscreen when viewer and file are from different domains

### ISSUE THREAD

**Issue by flaviorocks** [intbot/ng2-pdfjs-viewer#141]
For my setup I have the viewer file coming from a CDN and the file coming from a different domain. 
I pass the url to `[viewerFolder]="https://my-cdn/pdfjs"` and the encoded file URL to `[pdfSrc]="getEncodedFileUrl()"`. 

This setup renders the viewer and the pdf correctly, but, since the domain is not the same as the website, the browser doesn't allow fullscreen on the iframe automatically, as is the case of the [demo](https://ng2-pdfjs-viewer.azurewebsites.net/home), which has all the url's coming from the same domain.

To allow the iframe to have fullscreen in this scenario, the iframe would need to set the property allowfullscreen to true, ideally using the already defined variable to enable the fullscreen button. 
`<iframe [allowfullscreen]="fullScreen"></iframe>`.

**Comment by codehippie1** [comment]
@flaviorocks This is a unique issue. Please create a working sample - I will take a look when I have time. Also you may ask this question on SO.

**Comment by flaviorocks** [comment]
@codehippie1 Thanks for the reply. I will try to create a sample and ask on SO.
