### ISSUE TITLE
No fullscreen button 

### ISSUE THREAD

**Issue by KlausHans** [intbot/ng2-pdfjs-viewer#15]
I miss the fullscreen button, as seen here: http://mozilla.github.io/pdf.js/web/viewer.html

Any chance to add this option?

Another, slightly off topic question: How do you know the url options for the Mozilla viewer? I did not found them in the official documentation. 
I tried to use the latest version of gh-pages and the options doesn't work there at all ~~(but the fullscreen button is visible and functional, yay)~~.

**Comment by KlausHans** [comment]
Hm, seems to be a issue with the gh-pages. In Chome the fullscreen button is shown but not in Firefox or Edge.

**Comment by codehippie1** [comment]
Thanks for the suggestion. Will look into this.

**Comment by codehippie1** [comment]
@KlausHans  Implementing a parameter way to turning off full screen options. Will soon have an update

**Comment by codehippie1** [comment]
@KlausHans This feature  is available now using [fullScreen]
