### ISSUE TITLE
Single page viewer

### ISSUE THREAD

**Issue by tigrenok00** [intbot/ng2-pdfjs-viewer#152]
Hi!
Did anybody find a way to display single pages only, without scrolling the full document? I know PDF.js has a SinglePageViewer but it is much more convenient to use this component.
Thanks!

**Comment by codehippie1** [comment]
@tigrenok00 I am planning to bump pdfjs version within this library. Once I do - I will try to expose this as a parameter

**Comment by codehippie1** [comment]
The upgrade is underway to v 4.x. Closing as this is tracked under enhancement.
