### ISSUE TITLE
Canvas mouse events

### ISSUE THREAD

**Issue by tigrenok00** [intbot/ng2-pdfjs-viewer#153]
Hi,

I'm trying to capture mouse events on a page canvas, but this doesn't seem to get triggered. 
When I used PDF.js directly this was working, but using this plugin it does not.
Any idea how to achieve it?
I also tried to not set the cursor to hand, and tried disabling text and annotation layers (which did not work - I saw another issue opened about it), but it didn't help.

```
    (
      this.pdfViewer.PDFViewerApplication.pdfViewer._pages[0]
        .canvas as HTMLElement
    ).onmousedown = (e) => {
      console.log('onmousedown');
      console.log(e);
    };
```

**Comment by codehippie1** [comment]
@tigrenok00 Though the library exposes underlying pdfjs object -  The requested issue is beyond the capabilities and vision of this wrapper. I have plans to upgrade the underlying pdfjs to latest stable version. You may check it then. Till then look for solutions via stackoverflow with this library as tag.

**Comment by CristianPumaES6** [comment]
> Hi,
> 
> I'm trying to capture mouse events on a page canvas, but this doesn't seem to get triggered.
> When I used PDF.js directly this was working, but using this plugin it does not.
> Any idea how to achieve it?
> I also tried to not set the cursor to hand, and tried disabling text and annotation layers (which did not work - I saw another issue opened about it), but it didn't help.
> 
> ```
>     (
>       this.pdfViewer.PDFViewerApplication.pdfViewer._pages[0]
>         .canvas as HTMLElement
>     ).onmousedown = (e) => {
>       console.log('onmousedown');
>       console.log(e);
>     };
> ```

Hola, tuve un requerimiento en el cual querían ver la información de cada punto del chart.
lo que hice fue solo, activar todos los tooltip antes de tomar captura al elemento canvas.
Fue todo un dolor de cabeza.

Te mando una captura para que veas como quedo haber si te da una idea.

Saludos y suerte!

![image](https://user-images.githubusercontent.com/29841048/129152981-f7ce6736-6f26-4a26-865b-34db88bfd977.png)

**Comment by codehippie1** [comment]
@CristianPumaES6 The library is to display PDF, I am unsure if I can help with specific requirements your clients have. Ask a question on SO with ng2-pdfjs-viewer as tag

**Comment by scry-UrjitDesai** [comment]
Any updates on this? Can we have mouse events on the underlying canvas ?
