### ISSUE TITLE
Some content of PDFs not rendering in latest browsers

### ISSUE THREAD

**Issue by lpuccio** [intbot/ng2-pdfjs-viewer#157]
We're having an issue with some of the text of our documents not rendering on the canvas. It seems that the newest browsers (Chrome 92, Edge) required an update to PDF.js. You may want to update the version of PDF.js that you bundle with the app. Meanwhile, is there a way to get ng2-pdfjs-viewer to use an external version of pdfjs? 

Thanks.

The PDFjs issue that was updated is detailed here: 

https://github.com/mozilla/pdf.js/issues/13870

**Comment by szh** [comment]
As you can see [here](https://github.com/mozilla/pdf.js/pull/12924/files), this is literally a one line fix in pdf.js. I manually editing node_modules\ng2-pdfjs-viewer\pdfjs\build\pdf.worker.js with this change and it fixes it. So maybe in the interim we can just get a patch to that file while we wait on a full update of pdf.js?

**Comment by codehippie1** [comment]
For now, manually change it and send in a pull request. I will merge and
provide a build. (Please note - I would be doing a pdfjs version bump soon)

Also- If you would like to be part of this project - Let me know, I will
add you to the team.

Code

**Comment by chriseenberg** [comment]
Any news on when the PR will be approved? I need this change also, and cannot edit node_modules as it gets built on a server with a fresh node_modules folder.

**Comment by codehippie1** [comment]
The upgrade is underway to v 4.x. This is tracked under enhancement.
