### ISSUE TITLE
Please, SRC DATABASE

### ISSUE THREAD

**Issue by LuizWeitz** [intbot/ng2-pdfjs-viewer#159]
Hello,

first excellent project

I need help in the src, my case is, I register the url of the pdf of another server in my database, then I need to pass this url to the pdf src for it to read, but it doesn't read

example of code 

  "  ng2-pdfjs-viewer pdfSrc="{{book.read}}"></ng2-pdfjs-viewer   "
  

but when I do that nothing happens, nor does the console get an error

**Comment by codehippie1** [comment]
This seems to be how to use library question. Please create a stack
overflow question with this library as tag along with code sample.
Community will help.

Code

**Comment by LuizWeitz** [comment]
Thanks
