### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by ani2479** [intbot/ng2-pdfjs-viewer#16]
Hi,

I'm trying to use this on my CLI-Project. I copied the pdfjs folder on my assets, but it keeps saying that 'ng2-pdfjs-viewer' is not a known element:
1. If 'ng2-pdfjs-viewer' is an Angular component, then verify that it is part of this module.

Any ideas? I imported on app.module.ts and nothing.

Thank you in advance

**Comment by ani2479** [comment]
I fixed. 

Thank you

**Comment by vishnu-dev** [comment]
@ani2479 How did you fixed it?

**Comment by ani2479** [comment]
Hi, We added it to the tsconfig.app.config

**Comment by vishnu-dev** [comment]
Ok. Thanks @ani2479 .
