### ISSUE TITLE
🚀 Help enabled hand tool by default  🍔🍔

### ISSUE THREAD

**Issue by CristianPumaES6** [intbot/ng2-pdfjs-viewer#163]
Hello :hamburger: ,
How can I make the :hand:  **hand tool** option appear enabled by default.

It is very useful to move around, a common user would not know that this tool exists, so I want it to be activated by default.

![image](https://user-images.githubusercontent.com/29841048/129154492-50037e72-8006-4992-8152-dbf7decf6441.png)

Greetings from Peru!
Thanks

**Comment by CristianPumaES6** [comment]
:rocket:

**Comment by codehippie1** [comment]
Use 'cursor' attribute. It is mentioned in documentation.
