### ISSUE TITLE
embed file pdf have password

### ISSUE THREAD

**Issue by hoangquockhanh** [intbot/ng2-pdfjs-viewer#165]
can you update attribute to add password when embed file pdf have password (in lib pdfjs have attribute to add password like this: this.loadingTask = this.pdfjsLib.getDocument({ url: url, password: password });
)

sorry my english not good

**Comment by codehippie1** [comment]
I am a bit lost here, Can you send in a PR?

**Comment by codehippie1** [comment]
No follow-ups. Closing
