### ISSUE TITLE
Error while RenderPageRequest: page 0

### ISSUE THREAD

**Issue by obadaka961** [intbot/ng2-pdfjs-viewer#172]
> This error occurs when opening some pdfs.

    getOperatorList Error: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function at() { [native code] } could 
    not be cloned.
    at MessageHandler.postMessage (http://localhost:4200/assets/pdfjs/build/pdf.worker.js:55977:19)
    at MessageHandler.send (http://localhost:4200/assets/pdfjs/build/pdf.worker.js:55658:10)
    at TranslatedFont.send (http://localhost:4200/assets/pdfjs/build/pdf.worker.js:33073:15)
    at http://localhost:4200/assets/pdfjs/build/pdf.worker.js:31006:20

> After tracking the error I found the reason.

    Warning: getOperatorList - ignoring errors during "RenderPageRequest: page 0" task: "DataCloneError: Failed to execute 
    'postMessage' on 'DedicatedWorkerGlobalScope': function at() { [native code] } could not be cloned.".

> The reason that this message could not be cloned that there is a property in the message's data which is a function.
> That happens when using postMessage to send the following message:

![bug](https://user-images.githubusercontent.com/36939328/135709832-ac850d02-c12a-4688-b444-d79f61c6ea6c.png)

> Property widths has the following property:

![bug](https://user-images.githubusercontent.com/36939328/135709899-f431e192-6bb2-4f7d-b20d-be544acb7f09.png)

> This error makes ng2-pdfjs-viewer to cancel rendering process. Therefore, a lot of data is missing in the preview.
> Is there any solution to avoid this error?

**Comment by lin5787** [comment]
I saw the same error yesterday, which let me to this page, but then I discovered that https://github.com/intbot/ng2-pdfjs-viewer/issues/157 appears to be addressing the same issue and I can now confirm it does.

**Comment by codehippie1** [comment]
The upgrade is underway to v 4.x. Closing as this is tracked under enhancement.
