### ISSUE TITLE
How Retrive Blob loading

### ISSUE THREAD

**Issue by Toso82** [intbot/ng2-pdfjs-viewer#186]
Hi i have latest version i want to know it is possible to have the blob file loading on file open of pdf component.

**Comment by codehippie1** [comment]
blob and bite array is supported. Read documentation - https://ng2-pdfjs-viewer.azurewebsites.net/bytearray

**Comment by codehippie1** [comment]
@Toso82 - Since I didn't hear from you after supplying documentation, closing this

**Comment by Toso82** [comment]
@codehippie1 Sorry I see now I know that I can load blog file inside but my problem it is if I load file with pdf components buttons.. There is nothing can use to retrieve blob load inside?

**Comment by codehippie1** [comment]
This request is beyond the scope of this project. Create a SO question for ideas.
