### ISSUE TITLE
Compatibility issue with Angular 13.0.4

### ISSUE THREAD

**Issue by shash7976** [intbot/ng2-pdfjs-viewer#188]
Hi @codehippie1,
Hope you are doing great now

I'm still facing this compatibility issue on the server 

<img width="790" alt="image" src="https://user-images.githubusercontent.com/83197691/166586719-431301ac-cb1a-430b-a5c5-5af75c928906.png">

Package.json contain 
"ng2-pdfjs-viewer": "^6.0.2",

if I run `npm update ng2-pdfjs-viewer` on my local machine I get an error 
![image](https://user-images.githubusercontent.com/83197691/166586597-fcaa0a42-f51d-4358-a641-27f472512a46.png)

Could you please let me know what can be done...
All our production deployments are failing due to this issue

TIA

**Comment by codehippie1** [comment]
As I said in the other issue, upgrade the package to 13.2 and you should be good.
