### ISSUE TITLE
Plans on updating PdfJs viewer

### ISSUE THREAD

**Issue by angelaki** [intbot/ng2-pdfjs-viewer#189]
I've updated the pdfjs binaries and everything works out of the box - except messages / events. E.g. onDocumentLoad isn't working any more. Any plans on updating the binaries?

**Comment by RobRoyce** [comment]
Adding a +1 for 2.15.349+

> new experimental editor mode in the viewer

Would be awesome!

**Comment by codehippie1** [comment]
This is a bit challenging and tedious task. Messages / Events are not inherently supported by PDFJS. Similarly several other enhancements are added to existing PDFJS library. This is on my radar and would be done soon.

**Comment by codehippie1** [comment]
The upgrade is under way to v 4.x. Closing as this is tracked under enhancement.
