### ISSUE TITLE
Angular 14 compatibility

### ISSUE THREAD

**Issue by sgabb** [intbot/ng2-pdfjs-viewer#190]
Hello, any plan to update compatibility and dependency to Angular 14?

**Comment by codehippie1** [comment]
Soon, Will do in next couple of weeks

**Comment by MotassemJa** [comment]
Any updates on this? :)

**Comment by Kreash** [comment]
really want support for angular 14 =)

**Comment by dereekb** [comment]
This is the last dependency I need for upgrading a project to Angular 14, so I'll probably start on a PR here soon. I don't believe there will be any particular changes between 13 and 14 that would cause any issues.

**Comment by codehippie1** [comment]
I am out of country till school opening. But I should be able to merge changes from your PR. Please let me know once it is ready.

**Comment by dereekb** [comment]
PR is created. Double check the changes, but all I did was bump the versions, create an ng-package.json file since they're required now apparently, merged those module declaration together, and ran build.

**Comment by hemant-parmar** [comment]
Awaiting for the update .. need it badly.. 4 apps affected.. Please help.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! While resolving: cops@0.0.0
npm ERR! Found: @angular/common@14.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.2.2" from ng2-pdfjs-viewer@13.2.2
npm ERR!   ng2-pdfjs-viewer@"*" from the root project

**Comment by hemant-parmar** [comment]
@dereekb 
> In the meantime if anyone is blocked by this you can pull down a special branch I've got that hosts the dist files directly:

You mean the given reference  "ng2-pdfjs-viewer": "git+...."    should be added to the package.json file under dependencies?

**Comment by MotassemJa** [comment]
> @dereekb
> 
> > In the meantime if anyone is blocked by this you can pull down a special branch I've got that hosts the dist files directly:
> 
> You mean the given reference "ng2-pdfjs-viewer": "git+...." should be added to the package.json file under dependencies?

Yes you can add it to your package.json. But this is a temporary solution

**Comment by hemant-parmar** [comment]
@dereekb 
I used your link as a temp solution in package.json. But got the below error:
`Error: NG04002: Cannot match any routes. URL Segment: 'assets/pdfjs/web/viewer.html'`

Note that I have the below in the angular.json file's options-assets (it was there for the prev version's implementation)
`              {
                "glob": "**/*",
                "input": "node_modules/ng2-pdfjs-viewer/pdfjs",
                "output": "/assets/pdfjs"
              }
`

Then I manually copied the the `node_modules/ng2-pdfjs-viewer/pdfjs` folder to the assets folder and then it worked.
But is this the right way?
I was not required to do this manual copy-paste earlier. Did I miss anything in implementing the temp solution?

**Comment by dereekb** [comment]
Looks like the `dist` build didn't copy anything to `assets`, or rather there is no assets folder.

https://github.com/dereekb/ng2-pdfjs-viewer/tree/feat/angular14-dist

However, it looks like all the assets content is in `/pdfjs` instead of `/assets/pdfjs`. 

https://github.com/intbot/ng2-pdfjs-viewer

My "guess" is that the assets folder isn't used anymore or is used to prevent non-breaking changes between the previous updates, and the documentation should be updated to reflect the pdfjs folder instead of `assets/pdfjs`.

The assets configuration for ngPackage is for the new `/pdfjs` folder currently.

https://github.com/intbot/ng2-pdfjs-viewer/blob/25973eb38d3676666c09f38b045fd85334a18f41/package.json#L7

**Comment by codehippie1** [comment]
I will return from vacation on Sep 12th. I could merge this the same week. Anyone interested in being a maintainer, let me know, would be happy to share the responsibilities.

**Comment by NotTheSamAdamsGuy** [comment]
Any updates on the release for this? Thank you!

**Comment by Toso82** [comment]
When exit new release?

**Comment by sgabb** [comment]
Thanks, that's great!
