### ISSUE TITLE
Doesn't hide scaleSelectContainer on mobile when use 2 ng2-pdfjs-viewer on 1 page

### ISSUE THREAD

**Issue by HoaBanMC** [intbot/ng2-pdfjs-viewer#191]
I have this issues on mobile when use 2 div show/hide 2 components  ng2-pdfjs-viewer on page:

![image](https://user-images.githubusercontent.com/12248286/180152458-02a9f148-e0c5-45f8-b762-3b1544487ce1.png)
![image](https://user-images.githubusercontent.com/12248286/180152527-b8186158-2982-46ee-a5b0-e3133b60a2fe.png)

```
<div>
  <button (click)="changeTab(1)">
    tab1
  </button>
  <button (click)="changeTab(2)">
    tab2
  </button>
</div>
<div class="contain">
  {{currentLink}}
  <div class="tab1" [class.show-tab]="currentTab === 1">
    <ng2-pdfjs-viewer [pdfSrc]="src1"></ng2-pdfjs-viewer>
  </div>
  <div class="tab2 " [class.show-tab]="currentTab === 2">
    <ng2-pdfjs-viewer [pdfSrc]="src2"></ng2-pdfjs-viewer>
  </div>
</div>
```
viewer.css on second div doesn't work
![image](https://user-images.githubusercontent.com/12248286/180153305-10955180-1efb-4999-a2b5-78c2a1fe91b4.png)

Please help, Thanks!

**Comment by codehippie1** [comment]
What is the issue? What are the steps to reproduce it? I am unclear on this.

**Comment by HoaBanMC** [comment]
Hi codehippie1, thanks for reply. This error occurs on mobile and I forked my own then fixed this error by adding '!important' after that line. I will close this issuses now.
