### ISSUE TITLE
How to change Background color?

### ISSUE THREAD

**Issue by nina-fahmida** [intbot/ng2-pdfjs-viewer#195]
Please help me to change **Background Color** other than black.

![image](https://user-images.githubusercontent.com/51970447/196372957-931ee601-e987-44a8-bda5-01f5430bfdaa.png)

**Comment by codehippie1** [comment]
Can be easily done without the library's help.

`document.getElementById('viewerContainer').style.backgroundColor = "red";`

I will create an enhancement to add this into one of the parameters.

![image](https://user-images.githubusercontent.com/18332214/211376257-af8f6a4e-f22b-4eb2-8f43-01c32d9a32cd.png)
