### ISSUE TITLE
PDF viewer height issue

### ISSUE THREAD

**Issue by shakram02** [intbot/ng2-pdfjs-viewer#2]
Hello,

The pdf viewer appears in an extremely small height.

![image](https://user-images.githubusercontent.com/10996982/40871289-2d152f78-6639-11e8-8d4f-9781e144c162.png)

`HTML`

![image](https://user-images.githubusercontent.com/10996982/40871270-e3e4e3d4-6638-11e8-8b83-ec4b22d599ae.png)

`TS`

![image](https://user-images.githubusercontent.com/10996982/40871276-f24c1c4e-6638-11e8-831a-972848a5cca5.png)

My guess is that the pdfjs still thinks that the content is empty when I call refresh, what do you think?
Not sure if the warnings are relateable.

**Comment by codehippie1** [comment]
Let me take a look

**Comment by codehippie1** [comment]
As a quick fix, set height of your container to `900px`, like below. [And optionally flip its visibility till button is clicked to load pdf]

<div style="height: 900px;">
  <ng2-pdfjs-viewer #pdfViewer></ng2-pdfjs-viewer>
</div>

**Comment by codehippie1** [comment]
It makes more sense for the viewer to adapt the size of the container. I have updated the samples to reflect a case like yours. Closing the issue for now. Keep me posted if this suffice.

**Comment by shakram02** [comment]
Thanks!,  I'll tell you

**Comment by shakram02** [comment]
It's working with the fix. But this won't play well with mobile devices I guess

**Comment by hexadecy** [comment]
In my case, I use:
```
html, body {
	height: 100%;
	margin: 0;
	overflow: hidden;
}
```

**Comment by prashanthyD** [comment]
> It makes more sense for the viewer to adapt the size of the container. I have updated the samples to reflect a case like yours. Closing the issue for now. Keep me posted if this suffice.

i am unable to get height of ng2 pdfjs viewer from my welcome component

**Comment by MarkPieszak** [comment]
For others who might run into this.
Try and use a templateRef on a parent div, `<div #wrapper>`, grab it via `@ViewChild('wrapper') private wrapper: ElementRef` and inside ngAfterViewInit() update the style.height to something appropriate to the window outerHeight at that moment.
