### ISSUE TITLE
Let's mention each other's project in the README.md

### ISSUE THREAD

**Issue by stephanrauh** [intbot/ng2-pdfjs-viewer#21]
It seems we've started the same project simultaneously and independently of each other. Would you mind to mention my project in the readme file? In return, I'd do so, too. Plus, I'd like to blog about your project.

Project coordinates:
https://www.npmjs.com/package/ngx-extended-pdf-viewer
https://github.com/stephanrauh/ngx-extended-pdf-viewer

**Comment by stephanrauh** [comment]
@codehippie1 May I "ping" you? 

One of the thing fascinating me about open source is that the open source communities are so open and welcoming. So I'd like to support your project, even if it's the direct competition of my project. But before doing that, I'd like to reach out to you. So I'm waiting for your "ping back".

Thanks in advance,
Stephan

**Comment by codehippie1** [comment]
Hey Stephan,

Been away for a long time. Thanks for writing to me.

In open source world; there are no competitions. It is just some of us have
too much time in our hand to do similar work. underscore and lodash, react
and angular - the list goes on. :-)

I created the library as a result of below discussion. I never found a
generic library, hence gone ahead and wrapped the code to help others.
https://stackoverflow.com/questions/49309797/rdlc-local-report-viewer-for-asp-net-core-and-angular2-0/50009151#50009151


I am glad you wrote to me, and good luck with your project. When I get to
update my project, I will mention your library as well (I already have
mentioned few other libraries in GitHub and is a big fan of some of them)

/Code

**Comment by stephanrauh** [comment]
Thanks for the kind words! You're right about the "too much time" bit. I wrote my library in a professional setting, but chose to do it in my spare time. That allowed me to publish the library. I believe it was worth it, but "too much time to spare" nails it. :)

**Comment by stephanrauh** [comment]
BTW, I just looked at your implementation. I hoped I can learn one or two things. Whow, you've simply wrapped the PDF viewer in an iFrame? That's a clever solution. It also explains why your viewer is more reliable than my viewer (if I'm to believe the complaints in the bug list). So we've got two radically different approaches. Awesome!

**Comment by codehippie1** [comment]
Added a ref to your project.

**Comment by stephanrauh** [comment]
Awesome, thanks!

**Comment by stephanrauh** [comment]
The entire section mentioning other projects has vanished. Did you delete that by mistake?

```
## Other projects worth mentioning
1. Angular 5+ [ng2-pdf-viewer](https://github.com/VadimDez/ng2-pdf-viewer)
2. AngularJS [angular-pdfjs-viewer](https://github.com/legalthings/angular-pdfjs-viewer)
3. Angular [ngx-extended-pdf-viewer](https://github.com/stephanrauh/ngx-extended-pdf-viewer)
```
