### ISSUE TITLE
Use minified versions of pdfjs *.js dependencies

### ISSUE THREAD

**Issue by JWess** [intbot/ng2-pdfjs-viewer#22]
When the pdfjs viewer gets loaded, it loads the following three large JS files:
![image](https://user-images.githubusercontent.com/8697891/53360777-765d7700-3904-11e9-8663-7135ffe2f1f5.png)

It would be nice if the component defaulted to use the minified versions of these files to save load time. The minified versions of each of the three files are located here:
https://github.com/mozilla/pdfjs-dist/tree/master/build

Perhaps the component could have a [debug] input, and when set to true, it would use the full version of each of the JS files (with sourcemaps).

This is unrelated, but you should probably update your README to list the following as a way to copy pdfjs to the assets directory:
![image](https://user-images.githubusercontent.com/8697891/53361391-a8230d80-3905-11e9-97e1-b431ada5cff3.png)

**Comment by codehippie1** [comment]
I started working on this. Will have a new updated build available soon. @JWess Thanks for the suggestion on README.

**Comment by codehippie1** [comment]
@JWess The minified versions of js files are available now. A gulp task is added.

**Comment by codehippie1** [comment]
@JWess Your suggestion is also incorporated in README. Closing this issue

**Comment by Cselt** [comment]
As I can see still not the minified versions are used.

Right now if you create a new project and follow the steps to copy the assets from node_modules you will have a directory with the size of ~11Mb.

However if you modify _viewer.html_ to use minfied files and remove unnecessary files (unminified files and mappings) you will have only ~3.7Mb.

Would it be possible to create a minified version of the application with only the really necessary and minified files? It could be called _pdfjs-min_ and so you could decide which version you would like to use (Choose the right directory in you _angular.json_). 

What do you think?
