### ISSUE TITLE
Update versions for Angular 16

### ISSUE THREAD

**Issue by timothyBrake** [intbot/ng2-pdfjs-viewer#227]
Currently we need to build using --force as dependencies go up to Angular 15. Would be great to have the versions updated to Angular 16 so --force is not needed.

**Comment by SoyDiego** [comment]
+1

**Comment by timothyBrake** [comment]
There’s a pill request here for Angular 16. https://github.com/intbot/ng2-pdfjs-viewer/pull/226

**Comment by markh42** [comment]
+ 1

**Comment by DmitrySidorukITRex** [comment]
+1

**Comment by shashi-chemist2u** [comment]
+ 1

**Comment by raiworld81** [comment]
+1

**Comment by JanAelb** [comment]
+1

**Comment by codehippie1** [comment]
This is completed.
