### ISSUE TITLE
Load pdf with specified pages

### ISSUE THREAD

**Issue by Jeya-Prakash** [intbot/ng2-pdfjs-viewer#23]
Hi , Is there any option to load the particular specified pages alone?
For example: 
How to load [2nd] (or) [2nd and 3rd] page alone in the PDF viewer from a 7 page PDF document

**Comment by Jeya-Prakash** [comment]
@codehippie1 Hi waiting for your reply :)

**Comment by codehippie1** [comment]
Hi Jeya. I don't think it is straight-forward to achieve it with this component. You may need to use the pdfjs directly or get hold of the underlying component in viewerjs.

**Comment by codehippie1** [comment]
I will look into the exposed features of pdfjs and try to incorporate it if it is a feature supported at core level. This might take a while.

**Comment by Jeya-Prakash** [comment]
Thanks alot.

**Comment by codehippie1** [comment]
@Jeya-Prakash I got some time today and integrated this into the component. Now I have exposed `PDFViewerApplicationOptions` and `PDFViewerApplication`. This will allow everyone to access a lot more hidden features and change them programmatically. So, not just page numer, a lot can be changed directly once the document is loaded.

**Comment by codehippie1** [comment]
@Jeya-Prakash Closing as the underlying `PDFViewerApplicationOptions` object is exposed as `public`. If PDFJS supports it, you can achieve this with a bit of customization.
