### ISSUE TITLE
Change default locale

### ISSUE THREAD

**Issue by Luiz-Otavio-Dorigon** [intbot/ng2-pdfjs-viewer#24]
I would like to know how to switch between 2 local pt-BR and en-US?

**Comment by codehippie1** [comment]
Let me look into it. Will have an update in few days.

**Comment by Luiz-Otavio-Dorigon** [comment]
I give up waiting :(

**Comment by codehippie1** [comment]
@Luiz-Otavio-Dorigon Sorry for the delay. Unfortunately I am the only developer on this library, it is started as a hobby and went on to have several downloads quite unexpectedly. As I have a regular 9-5er(which is my bread winner), I try to keep this project up to date and bug free using a limited time.

Thanks for understanding, I just fixed this issue.
And once again, sorry for the wait. Hope you get to use the different locales this library offers now.

**Comment by codehippie1** [comment]
As per above comment, this feature is implemented. Hence closing this issue.
