### ISSUE TITLE
Add support for Angular 17

### ISSUE THREAD

**Issue by allenkepler-finastra** [intbot/ng2-pdfjs-viewer#243]
I created a PR for this
https://github.com/intbot/ng2-pdfjs-viewer/pull/242

**Comment by kongshu612** [comment]
Could you help to relese the support for Angular 17?

**Comment by maxrzaw** [comment]
@codehippie1 Any idea when you will have time to look into it and is there anything we can do to help with testing?

**Comment by codehippie1** [comment]
Doing now. Just back from a break today. 🙃

**Comment by codehippie1** [comment]
@allenkepler-finastra Would you like to be added to the "team" for this project?

**Comment by codehippie1** [comment]
@maxrzaw @kongshu612 @allenkepler-finastra  Released to npm - Version 17.0.2. If you folks see any issues, let me know here.

**Comment by allenkepler-finastra** [comment]
> @allenkepler-finastra Would you like to be added to the "team" for this project?

sure

**Comment by codehippie1** [comment]
@maxrzaw @allenkepler-finastra I invited both of you to be part of this. Your help is much appreciated.
