### ISSUE TITLE
Capture pdf finished loading event in angular 2

### ISSUE THREAD

**Issue by Jeya-Prakash** [intbot/ng2-pdfjs-viewer#25]
How to capture pdf finished loading event in angular 2 ?

**Comment by codehippie1** [comment]
I just started looking into it. This will be available in next release.

**Comment by codehippie1** [comment]
Unfortunately I couldn't include it in the last release. My focus is shifted to events now, expect this in one of upcoming builds.

**Comment by codehippie1** [comment]
@Jeya-Prakash @vunb @Klaushans - This feature is implemented. Quite simple to use. Try in lines of `(onDocumentLoad)="testPagesLoaded($event)""`

**Comment by Jeya-Prakash** [comment]
Thanks mate 🔥

**Comment by Halfist** [comment]
It doesn't work for me. Could you please help? I'm autoloading the document. I tried both attribute `(onDocumentLoad)="onDocumentLoad($event)"` and reference `this.pdfViewerRef.onDocumentLoad = () => {}` approach.
