### ISSUE TITLE
npm release version 1.0.1

### ISSUE THREAD

**Issue by agegendo** [intbot/ng2-pdfjs-viewer#27]
Hi,

I would like to know why

`npm install ng2-pdfjs-viewer --save`

always installs version 0.2.29. As I can see in your package.json, the most recent version should be 1.0.1, correct? If so, it seems that this version was not yet published to npm. Could you let me know when this will be done? 

Thanks in advance, Andreas

**Comment by codehippie1** [comment]
I just tried `npm install ng2-pdfjs-viewer --save` on a new project. It installed version 3.2.0 ("`ng2-pdfjs-viewer": "^3.2.0`",) and added this entry on `package.json`.

This is the latest version. I am closing this issue as it is not reproducible.

**Comment by agegendo** [comment]
Thanks for responding so quickly! After completely uninstalling version 0.2.29 first I managed to make a fresh installation of version 3.2.5. So the issue was only with my specific setup.
