### ISSUE TITLE
Can't show/hide buttons in new version 3.2.5

### ISSUE THREAD

**Issue by agegendo** [intbot/ng2-pdfjs-viewer#29]
Hi,

I'm having trouble showing and hiding the buttons that are being displayed at the top of the PDF-viewer.

This doesn't work in Html:

`<ng2-pdfjs-viewer [openFile]="false"
                      [download]="false"
                      [externalWindow]="false">
    </ng2-pdfjs-viewer>`

but also not in TypeScript:

`this.pdfViewer.openFile = false;
        this.pdfViewer.download = false;
        this.pdfViewer.externalWindow = false;`

Everything worked fine in version 0.2.29 (the one before the rewrite) but now I simply can't toggle the buttons. 
However what works fine in the above statements is `externalWindow`. Only the buttons are somehow broken.

Any hints to a solution greatly appreciated, thanks!

**Comment by codehippie1** [comment]
Looking into it,

**Comment by codehippie1** [comment]
@agegendo This is fixed an d a new version is released

**Comment by agegendo** [comment]
> 
> 
> @agegendo This is fixed an d a new version is released

Great, thanks!
