### ISSUE TITLE
Get current page number programmatically

### ISSUE THREAD

**Issue by amrishashok** [intbot/ng2-pdfjs-viewer#3]
Is there a way to get current page number and set a page number programmatically

**Comment by codehippie1** [comment]
This should be possible. I may need to change the interface to support this. It would be a bit before I get to this as I am pretty occupied with another project. You can download the source and try it or wait for me to add this.

**Comment by amrishashok** [comment]
Thanks for replying. I will try to implement this function. I have another question, is it possible to wait for a PDF to load before executing my function.

**Comment by codehippie1** [comment]
You need to look at PDFApplication usage within pdfjs to get events on pdf finished loading.

**Comment by amrishashok** [comment]
Ok thanks, I will look into that.

**Comment by codehippie1** [comment]
@amrishashok This is being implemented

**Comment by codehippie1** [comment]
@amrishashok You can set page number now. Also you can set named destinations. Other requests are not yet implemented.

**Comment by amrishashok** [comment]
Thanks!

**Comment by codehippie1** [comment]
@amrishashok - All of your feature requests are implemented. You can execute a function after pdf is loaded, set page#, and even get an event emitted when user scrolls through pages and get current page number. :)
