### ISSUE TITLE
Listen event after print

### ISSUE THREAD

**Issue by vunb** [intbot/ng2-pdfjs-viewer#30]
Hi, how to listen events from `ng2-pdfjs-viewer`? I want to listen event `afterPrint` to close the preview form automatically. Please suggest me how to do this?

**Comment by codehippie1** [comment]
Let me have a look at it. If it is straightforward to achieve it, I will include this as part of one of upcoming builds.

**Comment by codehippie1** [comment]
I am finally on this. Will be available in next build. Stay tuned

**Comment by codehippie1** [comment]
@vunb Finally, this is implemented. Use version 4.0.5 or above.

**Comment by codehippie1** [comment]
As per the comment, closing the issue. Feature request is completed

**Comment by vunb** [comment]
Great works! Thank you 👍
