### ISSUE TITLE
Too many console.log() in pdfjs/web/viewer.js

### ISSUE THREAD

**Issue by Aumkar** [intbot/ng2-pdfjs-viewer#31]
I can see there is a lot of console.log() in pdfjs/web/viewer.js added for testing purposes. Can we please have them removed? It is unnecessarily spamming console output in the developer's mode of browser

**Comment by Aumkar** [comment]
If you want, I can send PR for the same

**Comment by codehippie1** [comment]
I will remove them in the next build. Thanks for letting me know

**Comment by codehippie1** [comment]
console logs are removed. A new build is available in npm,
