### ISSUE TITLE
PDFLinkService.navigateTo: "null" is not a valid destination array

### ISSUE THREAD

**Issue by Geevo** [intbot/ng2-pdfjs-viewer#35]
Hi,

I'm receiving an error when trying to navigate to a specific section of a Pdf.

> PDFLinkService.navigateTo: "null" is not a valid destination array, for dest="3.2".

I'm running Electron/Angular 7 using the latest 3.5.1 which uses hashes to navigate routes.

Example: loading the following route
``` typescript
"dist/index.html#/docs"
```

Then specifying the nameddest
``` typescript
  _nameddest = '3.2';

  ngAfterViewInit(): void {
    this._service.getPdf().then(result => {
        this.pdfViewer.pdfSrc = result;
        this.pdfViewer.nameddest = this._nameddest;
        this.pdfViewer.refresh();
    });
  }
```

Perhaps something like this looks to be a similar issue to: 
[https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/71](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/71)

Any suggestions of how to workaround this would be greatly appreciated

Thanks,

**Comment by codehippie1** [comment]
@Geevo Let me have a look

**Comment by ananaghbar** [comment]
@Geevo is this fixed ? I'm facing the same issue with the same error :(

**Comment by ananaghbar** [comment]
@codehippie1 do you have any workaround for it ?

**Comment by codehippie1** [comment]
@ananaghbar @Geevo  - Any of you have a sample pdf(with named destinations) I can test this with?

**Comment by codehippie1** [comment]
@Geevo @ananaghbar Checking again - Do you have a sample pdf I can test this with?

**Comment by Geevo** [comment]
@codehippie1 sorry, totally missed these notifications. 
I don't have one that doesn't contain sensitive information right now. I will see if i can make a copy, strip out the content and keep the named dests.

**Comment by codehippie1** [comment]
@Geevo Closing due to lack of information and follow-ups
