### ISSUE TITLE
Pass HTTP headers along with URL

### ISSUE THREAD

**Issue by shreenil** [intbot/ng2-pdfjs-viewer#36]
My API is requesting Authorization header to access the files. How do i pass headers while passing URL in `pdfSrc`?

**Comment by codehippie1** [comment]
@shreenil I am afraid, I am not able to understand your issue. What is the url you are passing? The component does not make any http calls. You have to make the call to api and feed the resulting byte array into the component. Look at this example: https://ng2-pdfjs-viewer.azurewebsites.net/bytearray

**Comment by shreenil** [comment]
@codehippie1, If you look at this example [https://ng2-pdfjs-viewer.azurewebsites.net/home](https://ng2-pdfjs-viewer.azurewebsites.net/home), one can pass url of document in `pdfSrc`. 

Though, there is a note saying we need to have documents in 'assets' folder, I've tried passing my web API URL(which is returning byte stream) in `pdfSrc`, And it successfully loads the PDF if there is no authorization needed to access that webAPI.

Unfortunately, my web API is accessible to only 'Authenticated' users. So, i need to pass 'access-token' in API request headers to access the API URL.

Why i need to directly pass URL in `pdfSrc`? Because, it may be possible that my PDF is very lengthy and i may need to load it asynchronously. 

It would be great if I have option(feature) to pass headers if the URL is mobile.

**Comment by codehippie1** [comment]
I sort of understood the problem. Please post relevant code here, both server side and client side. I will try to get headers added if it is feasible.

Please note, source url is an underlying PDFJS's feature. Altering it may need tweaking.

**Comment by codehippie1** [comment]
@shreenil I did my research and this is not viable. viewerjs internally uses http request to set urls. (E.g .src etc). You will only be able to change http headers if the url is requested over javascript(Like ajax).

Please use the byte array mechanism. There you may be able to set http headers. (https://ng2-pdfjs-viewer.azurewebsites.net/bytearray )

Further info: https://stackoverflow.com/questions/24130004/adding-http-headers-to-window-location-href-in-angular-app
