### ISSUE TITLE
Events are not triggered

### ISSUE THREAD

**Issue by NikoKodzhabashev** [intbot/ng2-pdfjs-viewer#38]
Hey thank you very much for your work! I have a problem with the events, they receive my subscriptions but i am not getting any response. Thank you ;)

**Comment by codehippie1** [comment]
Please show me the code. Did you set the `viewerId` attribute? Without that attributes events won't work.

**Comment by NikoKodzhabashev** [comment]
Thank u!

**Comment by codehippie1** [comment]
Keeping this issue open as an FAQ reference. 💯

**Comment by codehippie1** [comment]
Closing now. Events should work when viewerId is set properly

**Comment by almalib** [comment]
> Закрытие сейчас. События должны работать, если viewerId установлен правильно

Hi. How to install it correctly? what should be passed to the viewerID?
