### ISSUE TITLE
Issue with onpagesloaded event and setting page number from code

### ISSUE THREAD

**Issue by Coder72** [intbot/ng2-pdfjs-viewer#39]
To the admin.
Its a really awesome control, however I found few issues like events are not working after setting the viewerid as well and i am setting the page number from code behind which is also not changing the page .
Need ur help in this regards.

**Comment by codehippie1** [comment]
Show me the code.

1. Please try the sample app and demo app. You may download both and try the events.
2. For page#, it can be set only at the time of loading now. i.e, subsequent changes are ignored.

**Comment by Coder72** [comment]
Any tentative  date when I can expect the  page change feature from code behind, hence itbis there is ng pdf js however its performance is too bad on huge documents or raster pdfs

**Comment by codehippie1** [comment]
@Coder72 There are few other requests/features being implemented now. Will get to this soon and look how feasible it is. Don't have a specific date yet.

**Comment by vishnu-dev** [comment]
@codehippie1 This is implemented in ng-pdf-viewer. Could you port from there?

**Comment by vishnu-dev** [comment]
I found a workaround for people needing this.

```
<ng2-pdfjs-viewer
          #pdfViewerOnDemand
          [pdfSrc]="pdfSrc"
          [page]="cur_page"
          viewerId="default"
        ></ng2-pdfjs-viewer>
```
```
@ViewChild('pdfViewerOnDemand') pdf_viewer;
this.pdf_viewer.iframe.nativeElement.contentWindow.PDFViewerApplication.page = page_num;
```

**Comment by codehippie1** [comment]
@vishnu-dev That is smart. This is exactly the way I am looking to expose some of the features, thus reducing the complexity of the component. Another user "Anthony" has a fork, exploring this mechanism, till I get to this - You may look at his fork to see what he has done accessing PDFViewerApplication and its options.

**Comment by codehippie1** [comment]
Precisely, this is the relevant code. 

```
public get PDFViewerApplicationOptions() {
    let pdfViewerOptions = null;
    if (this.externalWindow) {
      if (this.viewerTab) {
        pdfViewerOptions = this.viewerTab.PDFViewerApplicationOptions;
      }
    } else {
      if (this.iframe.nativeElement.contentWindow) {
        pdfViewerOptions = this.iframe.nativeElement.contentWindow.PDFViewerApplicationOptions;
      }
    }
    return pdfViewerOptions;
  }

  public get PDFViewerApplication() {
    let pdfViewer = null;
    if (this.externalWindow) {
      if (this.viewerTab) {
        pdfViewer = this.viewerTab.PDFViewerApplication;
      }
    } else {
      if (this.iframe.nativeElement.contentWindow) {
        pdfViewer = this.iframe.nativeElement.contentWindow.PDFViewerApplication;
      }
    }
    return pdfViewer;
  }
```

**Comment by codehippie1** [comment]
@vishnu-dev I got some time today and integrated this into the component. I also exposed `PDFViewerApplicationOptions` and `PDFViewerApplication`. This will allow everyone to access a lot more hidden features and change them programmatically. So, not just page numer, a lot can be changed directly once the document is loaded.

**Comment by vishnu-dev** [comment]
@codehippie1 That was a quick response. Thank you. When will this be released?

**Comment by codehippie1** [comment]
@vishnu-dev It is already released yesterday. Get latest version

**Comment by codehippie1** [comment]
Resolved. Closing as stated in above comment.

**Comment by almalib** [comment]
> I found a workaround for people needing this.
> 
> ```
> <ng2-pdfjs-viewer
>           #pdfViewerOnDemand
>           [pdfSrc]="pdfSrc"
>           [page]="cur_page"
>           viewerId="default"
>         ></ng2-pdfjs-viewer>
> ```
> 
> ```
> @ViewChild('pdfViewerOnDemand') pdf_viewer;
> this.pdf_viewer.iframe.nativeElement.contentWindow.PDFViewerApplication.page = page_num;
> ```

Hi, I can't figure out what the VIewerID is. What did you keep in 'default'?
