### ISSUE TITLE
How to use Uint8 pdf format inside pdfSrc tag to display PDF

### ISSUE THREAD

**Issue by GoodPotato** [intbot/ng2-pdfjs-viewer#4]
In my pdf.component.ts, pdfData property is pdf (base64 format), which is converted to Uint8 format. When I assign it to pdfSrc (inside .html file), the src is then "assets/pdfjs/web/viewer.html?file=<Uint8 format of pdf>", and therefore on my page the PDF is not loaded -> it throws an error that PDF file is missing. How can I make it that when I put Uint8 to pdfSrc, it will display the PDF inside the pdf viewer?

In my component.html file:
`<ng2-pdfjs-viewer pdfSrc="{{pdfData}}"></ng2-pdfjs-viewer>`

In my component.ts file:

>   ngOnInit() {
    this.pdfData = this.convertDataURIToBinary(PDF);
  }

 

>  convertDataURIToBinary(dataURI: string): Uint8Array {
>     let raw = window.atob(dataURI);
>     let rawLength = raw.length;
>     let array = new Uint8Array(new ArrayBuffer(rawLength));
>     let i: number;
>     for (i = 0; i < rawLength; i++) {
>       array[i] = raw.charCodeAt(i);
>     }
>     return array;
>   }

**Comment by codehippie1** [comment]
This should be straightforward, try something like below. The src needs to be set dynamically like below.

```
public openPdf() {
    let url = "url to fetch pdf as byte array";
    // url can be local url or remote http request to an api/pdf file. 
    // E.g: let url = "assets/pdf-sample.pdf";
    // E.g: https://github.com/intbot/ng2-pdfjs-viewer/tree/master/sampledoc/pdf-sample.pdf
    // E.g: http://localhost:3000/api/GetMyPdf
    // Please note, for remote urls to work, CORS should be enabled at the server. Read: https://enable-cors.org/server.html

    this.downloadFile(url).subscribe(
      (res) => {
        this.pdfViewer.pdfSrc = res; // pdfSrc can be Blob or ****Uint8Array** <--- Here**
        this.pdfViewer.refresh(); // Ask pdf viewer to load/reresh pdf
      }
    );
  }
```

**Comment by codehippie1** [comment]
Closing as an example is provided
