### ISSUE TITLE
how to add annotations in pdf

### ISSUE THREAD

**Issue by yexiaodong** [intbot/ng2-pdfjs-viewer#40]

**Comment by codehippie1** [comment]
If this is supported by Mozilla's pdf viewer, it would be available. My understanding is that, this is a viewer, not an editor and thus features of an editor is unavailable.

**Comment by codehippie1** [comment]
@yexiaodong I have exposed PDFViewerApplication object. This can be used to access all underlying features of PDFJS.

I could see an annotationlayer object available there.
You may refer to this article and devise a custom solution to achieve this.

https://usefulangle.com/post/94/javascript-pdfjs-enable-annotation-layer

**Comment by codehippie1** [comment]
@yexiaodong Any update?

**Comment by codehippie1** [comment]
Closing due to lack of follow-ups.
