### ISSUE TITLE
[IMPROVEMENT] Changelog and releases update

### ISSUE THREAD

**Issue by vishnu-dev** [intbot/ng2-pdfjs-viewer#41]
As large number of users use this wonderful library for Angular and updates being released frequently, it becomes necessary to maintain tags for commits . Subsequently updating release under the releases tab which will help users get what the need. Thanks.

**Comment by codehippie1** [comment]
@vishnu-dev Would you like to contribute to the project? Being the only active contributor now, it is difficult to keep up with this overwhelming usage increase; and thus with the documentation :-)

Community also need a wiki page, a FAQ, Common issues/Configuration mistakes and resolutions.

**Comment by vishnu-dev** [comment]
@codehippie1 Thanks for asking. I would surely like to help you out and contribute. I work for a company and won't be able to contribute more. But I'll try my best and pitch in whenever I can.

**Comment by codehippie1** [comment]
@vishnu-dev Thanks for showing interest. Greatly appreciate that. I am doing a full time at an organization, and had to squeeze in bug fixes here. Never would have ever thought this would be this big. :-)

The story behind this component is this SO question. OP is me.
https://stackoverflow.com/questions/49309797/rdlc-local-report-viewer-for-asp-net-core-and-angular2-0

I will add you as a contributor soon.

**Comment by codehippie1** [comment]
@vishnu-dev Started putting in release tags from V 6.0.1 onwards
