### ISSUE TITLE
font-weight issue on print through direct PDF viewer VS Downloaded PDF's.

### ISSUE THREAD

**Issue by MohammadTalhaKhan1** [intbot/ng2-pdfjs-viewer#42]
If print directed through the PDF viewer the font-weight getting Very light which cause a user readability issue to read and if print the downloaded PDF.
the font-weight printed as expected(Normal view). 
![github](https://user-images.githubusercontent.com/40386660/63439814-30631500-c448-11e9-9fa2-6c84b2b859c7.PNG)
![github2](https://user-images.githubusercontent.com/40386660/63439823-3527c900-c448-11e9-9314-ea09d4d6d01a.PNG)

**Comment by codehippie1** [comment]
Did you try the same on https://mozilla.github.io/pdf.js/web/viewer.html ? Printing functionality is provided by PDFJS, not this component. You may raise this bug against PDFJS

**Comment by MohammadTalhaKhan1** [comment]
Yeah, I have found the solution its a bug of PDFJS`s viewer.js
I have changed the value of the following variable:
![image](https://user-images.githubusercontent.com/40386660/63592591-595fe300-c5cb-11e9-92dd-786c362ba7f9.png)
var PRINT_RESOLUTION = 150; 
to
 var PRINT_RESOLUTION = 600; 
which is defined in the viewer.js in the node_modules I know its a patch but it works fine for me now.

**Comment by penihel** [comment]
There is a plain to upgrade the viewer.js file?

Threre is a new option to change this resolution in the newest version

**Comment by codehippie1** [comment]
The update is coming soon. Been bit busy focusing on another project.
