### ISSUE TITLE
IE -> An error occured when loading PDF 

### ISSUE THREAD

**Issue by shurkin** [intbot/ng2-pdfjs-viewer#45]
Browser : IE

When I try to open PDF file, the file is not loaded.

I have this error : 

![image](https://user-images.githubusercontent.com/19571307/64592487-6db62500-d3ac-11e9-889b-b9779707082a.png)

> PDF.JS v2.2.171 
Message : Unable to get propery ""headerReady" of null reference or undefined

Do you have any suggestions ?

Thank you.

**Comment by codehippie1** [comment]
Can you please reproduce this problem in a small working example?

Did you try downloading the demo app and using it in IE?

**Comment by codehippie1** [comment]
@shurkin  - Closing as user did not respond.
