### ISSUE TITLE
How to disable/restrict copy paste functionality of PDF content.

### ISSUE THREAD

**Issue by varun-nagar** [intbot/ng2-pdfjs-viewer#49]
How should I disable/restrict copy paste functionality of PDF content as no direct property is given to modify it.

**Comment by codehippie1** [comment]
@varun-nagar Please look into Mozilla's PDFJS documentation. If the underlying PDFJS component supports it, you can access it using the pdfviewerapplication property.

A quick googling gave me this: https://github.com/mozilla/pdf.js/issues/7964

**Comment by varun-nagar** [comment]
Thanks @codehippie1 pdfviewerapplication property(object) done the trick in solving my issue.
