### ISSUE TITLE
Compability with Angular 4

### ISSUE THREAD

**Issue by pupipipu** [intbot/ng2-pdfjs-viewer#5]
Hi there!

I got "ERROR in Metadata version mismatch found version 4, expected version 3". Angular 4 package is still using version 3 for now. Would you mind me forking the library and re-publishing it for angular 4 (with module version 3)?

Thanks

**Comment by codehippie1** [comment]
This should support Angular 2 and above. Please send or upload a working version where I can reproduce this issue

**Comment by codehippie1** [comment]
As there are no updates from OP, closing this issue
