### ISSUE TITLE
How to select text content of a specific page?

### ISSUE THREAD

**Issue by reyou** [intbot/ng2-pdfjs-viewer#50]
What I am trying to is something like below;

```
 @ViewChild("pdfViewerOnDemand") pdfViewerOnDemand: PdfJsViewerComponent;

// Can we have this available?
let entirePageTextContent = this.pdfViewerOnDemand.getTextContent(pageNumber);
```

**Comment by codehippie1** [comment]
Please ask this question on SatackOverflow, it would benefit others

This would be out of scope of this project right now, still

Try along these lines as the underlying `PDFViewerApplication` is accessible within the component.

```
var pdfDocument = this.pdfViewerOnDemand.PDFViewerApplication.pdfDocument,
  if (!pdfDocument) {
    return;
  }
```

Once you have access to the document, try methods described in these SO questions
https://stackoverflow.com/questions/20598292/getting-textcontent-pdf-js
https://stackoverflow.com/questions/40635979/how-to-correctly-extract-text-from-a-pdf-using-pdf-js
