### ISSUE TITLE
Does not build with ivy

### ISSUE THREAD

**Issue by biltongza** [intbot/ng2-pdfjs-viewer#52]
This package does not appear to build correctly when Ivy is enabled in Angular 8/9:
```
ERROR in node_modules/ng2-pdfjs-viewer/index.d.ts:3:22 - error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

  export declare class PdfJsViewerModule {
                       ~~~~~~~~~~~~~~~~~
```

There is an open issue in Angular about it: https://github.com/angular/angular/issues/32442

I have created a repo that reproduces this: https://github.com/biltongza/ng2-pdfjs-viewer-ivy-es2015

**Comment by petebacondarwin** [comment]
The build failure with ivy is due to the `module` property of [package.json](https://github.com/intbot/ng2-pdfjs-viewer/blob/master/dist/package.json#L25) being invalid.:

```json
  "module": "ng2-pdfjs-viewer.js",
```

There is no `ng2-pdfjs-viewer.js` file.

Instead this should be 

```json
  "module": "index.js",
```

**Comment by petebacondarwin** [comment]
See https://github.com/intbot/ng2-pdfjs-viewer/pull/55

**Comment by codehippie1** [comment]
@petebacondarwin Code is merged, should be good with next build

**Comment by KillerCodeMonkey** [comment]
Is it possible to release a new version with this fix? Thanks

**Comment by codehippie1** [comment]
Will update version in couple of days

**Comment by codehippie1** [comment]
@biltongza @petebacondarwin @KillerCodeMonkey New version is updated. V 5.0.3. 

@petebacondarwin - Thanks a lot for the fix.

Let me know if there are any issues.
