### ISSUE TITLE
Zoom Programatically w/o Refresh

### ISSUE THREAD

**Issue by JustinLutsky** [intbot/ng2-pdfjs-viewer#53]
Is there a basic example of zooming in, out, fit width, fit height, auto programatcially without refreshing? Trying to hide the toolbar and build a few custom buttons that call the same actions. Thanks!

Found this to be useful for zooming in and out, but can't find similar functions to zoom width, height, etc...

    this.pdfViewer.PDFViewerApplication.zoomIn();
    this.pdfViewer.PDFViewerApplication.zoomOut();

**Comment by codehippie1** [comment]
@JustinLutsky This is a how to question. Please ask these questions on stackoverflow, which benefits the whole community.

The options available in PDFViewerApplication is controlled by PDFJS. You may use it as you please. If you would like to build such functionality, you may refer to source code of viewer.js

Do something in line of after pdf is loaded.

```
var  pdfViewer = PDFViewerApplication.pdfViewer;
var  currentScaleValue = 'page-width'; // 'page-fit' etc
pdfViewer.currentScaleValue = currentScaleValue;
```
