### ISSUE TITLE
CSP unsafe-eval restricted

### ISSUE THREAD

**Issue by GitShaffi** [intbot/ng2-pdfjs-viewer#54]
Content Security Policy gets violated because unsafe-eval are not allowed in our webservers.
 
`viewer.js:3328 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' *.myapp.com "`.

The viewer doesn't work when the unsafe-eval is restricted.

**Comment by codehippie1** [comment]
@GitShaffi Please raise this concern to PDFJS project: https://github.com/mozilla/pdf.js/

This angular component uses Viewer.js internally.
