### ISSUE TITLE
fails when filepath includes a `#` symbol

### ISSUE THREAD

**Issue by AnalogJ** [intbot/ng2-pdfjs-viewer#67]
Hey,

I'm seeing the following error when using pdfjs-viewer to load a remote document that includes a `#` symbol

```
Message: Missing PDF
"https://my.domain.com/storage/documents/this_document_always#fails_because_of_hash_symbol.pdf".
undefined
```
looking at my console I see a request for 

```
VM115:1 Fetch failed loading: 
GET "https://my.domain.com/storage/documents/this_document_always".
```
which seems to imply that everything after the hash is being treated like a url fragment and is being dropped before the request is made. 

I've confirmed that I'm correctly url-encoding my `pdfSrc`

Any ideas how I can get this working? (I can't control the document names)

**Comment by codehippie1** [comment]
@AnalogJ ViewerJS from Mozilla interprets '#' as the start of parameters. 
https://github.com/mozilla/pdf.js/wiki/Viewer-options 

You may check and see how to escape this or raise this concern directly with them

**Comment by codehippie1** [comment]
@AnalogJ Were you able to find escape character for cases like this?

**Comment by ragauskl** [comment]
> @AnalogJ ViewerJS from Mozilla interprets '#' as the start of parameters.
> https://github.com/mozilla/pdf.js/wiki/Viewer-options
> 
> You may check and see how to escape this or raise this concern directly with them

Need to wrap the url in encodeURIComponent() as mentioned in link above, had same issue with '=' in query.
Can confirm that it fixed the problem.

See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file for more details
