### ISSUE TITLE
locale.properties not found.

### ISSUE THREAD

**Issue by guillemest** [intbot/ng2-pdfjs-viewer#74]
Hello I'm running my angular app on an IIS server everything is fine the library works fine except it doesn´t show the correct language which is spanish.  I'm using local="es-CL" I'm using angular material modal to display the viewer which works fine when I'm local the only issue is once the app is deployed on the server?

![error](https://user-images.githubusercontent.com/25377912/74376143-61e9e700-4dc0-11ea-8b53-68e5e6dc2bfa.PNG)

Thanks

**Comment by codehippie1** [comment]
This looks like something to do with MIME types. Thought it is out of scope of this project, here is something you can try. Add MIME type ".properties" in IIS. Also post this question on Stackoverflow for others to find help.

**Comment by codehippie1** [comment]
@guillemest Googling pointed me here. Look at last comment on mime types

https://github.com/mozilla/pdf.js/issues/6506
