### ISSUE TITLE
Update compatibility to Angular 9

### ISSUE THREAD

**Issue by orochies** [intbot/ng2-pdfjs-viewer#75]
Please update peer dependencies to avoid this alert

ng2-pdfjs-viewer@5.0.5 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by codehippie1** [comment]
@orochies  Will update this soon.

**Comment by silvl** [comment]
Is there an update?

**Comment by codehippie1** [comment]
Already on a higher angular version. Let me know if anyone see this issue anymore
