### ISSUE TITLE
Print feature broken on IOS and Android devices.

### ISSUE THREAD

**Issue by nilaybhima** [intbot/ng2-pdfjs-viewer#76]
The print feature prints the entire html page rather than pdf document on IOS and Android devices.

**Comment by seanke** [comment]
Also having this issue.

**Comment by codehippie1** [comment]
@nilaybhima Try this page directly and let me know the results. https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by nilaybhima** [comment]
Yes, this page is working.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by seanke** [comment]
> @nilaybhima Try this page directly and let me know the results. https://mozilla.github.io/pdf.js/web/viewer.html

It's working for me too! Nice work! One problem for me though, it's defaulting to Letter size and has shrunk the 3 pages onto one page and pages 4+ are missing. Am I doing something dumb?

**Comment by codehippie1** [comment]
@nilaybhima @seanke I won't be able to test this much as I don't have an ios device. I could use some help in fixing this issue. Let me know if you would like to send in a pull request.

**Comment by nilaybhima** [comment]
@codehippie1 Just a heads up, it doesnt work on Android either. It seems to be an issue with all mobile devices I would say.

**Comment by xubalachandran** [comment]
Any updates on this issue? for printing from mobile devices ?

using below packages 
 "@angular/animations": "~8.0.3",
 "@angular/cdk": "8.0.2",
 "@angular/common": "~8.0.3",
 "@angular/compiler": "~8.0.3",
 "@angular/core": "~8.0.3",
 "typescript": "~3.4.3"
 "ng2-pdfjs-viewer": "^5.0.7",

**Comment by Bierat1337** [comment]
issue still remains, print functionality atm not usable with android and ios.
-> shows empty page

**Comment by chrissteiner** [comment]
do you think this will ever be fixed? because this issue is now 4 years old .... ? I would really appreciate that @codehippie1 @allenkepler-finastra @Akxe @dereekb @shahmeet999 @urjitdesai @petebacondarwin @szh @anthonybriand @flaviorocks @grosa1

**Comment by codehippie1** [comment]
The upgrade is underway to v 4.x. Closing as this is tracked under enhancement.
