### ISSUE TITLE
Events when pdf loading failed

### ISSUE THREAD

**Issue by varshithayendapally** [intbot/ng2-pdfjs-viewer#79]
Is there a way to know (like an event) when the pdf loading failed for some reason?

**Comment by codehippie1** [comment]
@varshithayendapally There could be several reasons why a pdf might fail to load. As of now there are no signaling mechanism except you can change the error message being displayed. Let me see if I would be able to integrate this. As a sole contributor to this project, it would take me some time to get to new features.

**Comment by codehippie1** [comment]
The upgrade is underway to v 4.x. I should be able to address this using eventbus. Closing, but added enhancement tag and "After 4.x" milestone to track.
