### ISSUE TITLE
Disabling the textLayer in PDFjs

### ISSUE THREAD

**Issue by vishnu-dev** [intbot/ng2-pdfjs-viewer#85]
I need to disable the `textLayer` that is rendered above the canvas to reduce memory.
In PDFjs it is done with the code below,

`PDFJS.disableTextLayer = false`

How to do it using `ng2-pdfjs-viewer`?

**Comment by vishnu-dev** [comment]
Just figured it out, For people needing this,

    @ViewChild('pdfViewerOnDemand', {static: false}) pdfViewer;

    loadComplete() {
        this.pdfViewer.PDFViewerApplicationOptions.textLayer = false;
    }

**Comment by Paul75** [comment]
Hello,

For me that provoque error in console : PDFViewerApplicationOptions is not defined...

thanks

**Comment by vishnu-dev** [comment]
@Paul75 Load complete function should be called after document is loaded.

`(onDocumentLoad)="loadComplete()"`

**Comment by Avejack** [comment]
This is not working for me...

It did not change anything.

my html:
```html
<ng2-pdfjs-viewer #pdfViewer [pdfSrc]="data.pdfSrc" viewerId="anyId" (onDocumentLoad)="loadComplete()"></ng2-pdfjs-viewer>
```

my component:
```ts
  @ViewChild('pdfViewer', { static: false }) pdfViewer: PdfJsViewerComponent;
  
  loadComplete() {
    console.log('loadComplete');
    this.pdfViewer.PDFViewerApplicationOptions.textLayer = false;
    this.cdr.markForCheck();
  }
```

As you can see I am even trying to call "markForCheck()" to hopefully fire any change but nothing changes... The console.log gets logged to the console, but the textLayer is still rendered above the canvas.

**Comment by tigrenok00** [comment]
@Avejack Same here... Did you find a solution?

**Comment by Avejack** [comment]
For my use case - yes. But not for this problem - sorry.
