### ISSUE TITLE
How to hide entire toolbar in viewer?

### ISSUE THREAD

**Issue by kiranhpe** [intbot/ng2-pdfjs-viewer#89]
I'm don't want to show any controls in my application, how can hide entire toolbar?

![image](https://user-images.githubusercontent.com/22594383/80486377-b0972e00-8978-11ea-9a2c-be796ddf180e.png)

**Comment by FirstTimeInForever** [comment]
I was just scrolling through issues and saw yours. You probably already solved it, but if not, you can do something like this:
```
@ViewChild('viewer')
private viewer: PdfJsViewerComponent;

...

hideToolbar() {
    const appConfig = this.viewer.PDFViewerApplication.appConfig;
    appConfig.toolbar.container.parentElement.parentElement.style.display = "none";
    appConfig.viewerContainer.parentElement.style['top'] = 0;      
    appConfig.sidebar.outerContainer.querySelector("#sidebarContainer").style['top'] = 0;
}
```
You should run it in `onDocumentLoad` event.

**Comment by kiranhpe** [comment]
Cannot read property 'PDFViewerApplication' of undefined is the error i'm getting
