### ISSUE TITLE
Angular 9 compatibility

### ISSUE THREAD

**Issue by thimma11** [intbot/ng2-pdfjs-viewer#93]
Hi,
is it possible to use this library with angular 9?
I am trying to update my app to angular 9 and I'm getting the following error:

> Package "ng2-pdfjs-viewer" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0", would install "9.1.9")

**Comment by codehippie1** [comment]
@thimma11 Will be available in coming build

**Comment by codehippie1** [comment]
@thimma11 Upped to angular 11
