### ISSUE TITLE
[diagnosticLogs]="false" Doesn't Work

### ISSUE THREAD

**Issue by maks-humeniuk** [intbot/ng2-pdfjs-viewer#97]
`[diagnosticLogs]="false"` doesn't work. I can still see `PDF f758ecc7f3ab6219566158b17de59a9a [1.4 Mac OS X 10.11.5 Quartz PDFContext / Pages] (PDF.js: 2.2.171)` in console.

**Comment by codehippie1** [comment]
@Halfist Need to check this

**Comment by teosarpe** [comment]
any updates on this issue?

**Comment by thegeox** [comment]
any update on this issue?

**Comment by codehippie1** [comment]
The upgrade is underway to v 4.x. Diagnostic logs will be rewritten.
